import { freshState, normalize, stageOf, applyCare } from './game.js';
const $=s=>document.querySelector(s), key='pawful-days-v1';
let state=freshState();try{state=normalize(JSON.parse(localStorage.getItem(key)))}catch{}
let busy=false,walking=false,flowers=0,night=false,sound=false,audio,toastTimer,actionTimer;
const actions={feed:{label:'밥 주기',emoji:'🥣',text:'냠냠, 너랑 먹으니까 더 맛있어!',memory:'든든하게 밥을 먹고, 고마운 눈빛을 보냈어요.'},pet:{label:'쓰다듬기',emoji:'♡',text:'네 손은 언제나 따뜻해. ♡',memory:'손바닥에 얼굴을 기대고 가만히 눈을 감았어요.'},play:{label:'공놀이',emoji:'🎾',text:'한 번 더! 이번엔 내가 잡을게!',memory:'공을 따라 폴짝! 정원에 웃음이 가득했어요.'},walk:{label:'산책하기',emoji:'✿',text:'저기 꽃이 있어! 같이 찾아볼까?',memory:'꽃 세 송이를 찾아 우리만의 산책길을 만들었어요.'},rest:{label:'낮잠 자기',emoji:'☾',text:'조금만 잘게… 옆에 있어 줄 거지?',memory:'곁에서 새근새근, 달콤한 꿈을 꾸었어요.'}};
function save(){try{localStorage.setItem(key,JSON.stringify(state));$('#save-state').textContent='추억이 저장되었어요'}catch{$('#save-state').textContent='저장 공간을 확인해 주세요';toast('자동 저장이 어려워요. 기록 관리에서 추억을 내보내 주세요.')}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
function modal(html){$('#dialog-content').innerHTML=html;$('#dialog').showModal()}
function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const stage=stageOf(state.xp),names=['아기','청소년','어른'],limits=[100,250,500],base=[0,100,250];$('#dog').dataset.stage=stage;$('#dog-name').textContent=state.name;$('#stage-name').textContent=['세상이 궁금한 아기 강아지','장난기 가득한 청소년 강아지','든든하게 곁을 지키는 큰 강아지'][stage];$('#stage-badge').textContent=names[stage];$('#day').textContent=String(state.day).padStart(2,'0');$('#xp-label').textContent=state.xp>=500?'사랑이 가득해요':`${state.xp-base[stage]} / ${limits[stage]-base[stage]}`;$('#xp-bar').style.width=`${Math.min(100,(state.xp-base[stage])/(limits[stage]-base[stage])*100)}%`;$('#dog').style.width=`${window.innerWidth<=1000?[43,52,61][stage]:[35,43,51][stage]}%`;$('#growth-hint').textContent=stage===2?'다 자라도, 우리의 이야기는 계속돼요.':'작은 사랑이 모이면, 한 뼘 더 자라요.';$('#needs').innerHTML=[['food','포만감','#d8b77e'],['love','행복','#d3a79b'],['energy','기운','#98ae7d'],['bond','유대감','#a5b9ad']].map(([k,label,color])=>`<div class="need"><span>${label}</span><div class="need-track"><i style="width:${state[k]}%;background:${color}"></i></div><b>${state[k]}</b></div>`).join('');$('#milestones').innerHTML=[['첫 만남','작은 발자국이 우리 집에 온 날',0],['한 뼘 더 자라다','함께한 사랑 100 달성',100],['평생의 단짝','함께한 사랑 250 달성',250]].map(([title,desc,x],i)=>`<div class="milestone ${state.xp>=x?'done':'locked'}"><span>${state.xp>=x?'✓':'♡'}</span><div><strong>${title}</strong><p>${desc}</p></div></div>`).join('');$('#mission-dots').innerHTML=['feed','play','rest'].map(k=>`<span class="${state.daily.includes(k)?'checked':''}">${state.daily.includes(k)?'●':'○'} ${actions[k].label}</span>`).join('');$('#mission').textContent=state.dailyReward?'오늘의 행복을 모두 모았어요!':'밥도 먹고, 놀고, 쉬어 보기';}
function sparkle(emoji){for(let i=0;i<5;i++){const el=document.createElement('span');el.className='particle';el.textContent=emoji;el.style.setProperty('--dx',`${(i-2)*35}px`);el.style.left=`${45+Math.random()*10}%`;el.style.animationDelay=`${i*.1}s`;$('#particles').append(el);setTimeout(()=>el.remove(),2400)}}
function tone(){if(!sound)return;audio??=new AudioContext();audio.resume();[523.25,659.25,783.99].forEach((n,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.12;o.type='sine';o.frequency.value=n;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.045,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+.6);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+.65)})}
function finish(action){const old=stageOf(state.xp);state=applyCare(state,action);state.memories.unshift({day:state.day,text:actions[action].memory});state.memories=state.memories.slice(0,60);if(['feed','play','rest'].every(a=>state.daily.includes(a))&&!state.dailyReward){state.dailyReward=true;state.xp+=15;toast('오늘의 작은 행복 완성! 사랑 +15 ♡')}const next=stageOf(state.xp);save();render();tone();sparkle(actions[action].emoji);if(next>old){state.memories.unshift({day:state.day,text:next===1?'한 뼘 더 자랐어요. 발걸음이 제법 씩씩해졌어요.':'어느새 큰 강아지가 되어, 당신 곁을 든든하게 지켜요.'});save();setTimeout(()=>modal(`<div style="font-size:45px;text-align:center">🌱</div><h2>${escape(state.name)}가 한 뼘 자랐어요</h2><p>당신이 건넨 작은 사랑이 모여 ${next===1?'씩씩한 청소년':'든든한 어른'} 강아지가 되었어요. 앞으로도 함께 걸어요.</p><button class="primary" id="growth-close">계속 함께하기</button>`),600)}}
function care(action){if(busy){toast(walking?'반짝이는 꽃 세 송이를 찾아 주세요.':'잠깐만요, 지금 함께하는 중이에요.');return}busy=true;$('#speech').textContent=actions[action].text;$('#dog').classList.add('happy');if(action==='walk'){walking=true;flowers=0;$('#location').textContent='✿ 꽃향기 나는 산책길';$('#scene-caption').textContent='반짝이는 꽃을 눌러 주세요 · 0 / 3';$('#collect').classList.remove('hidden');placeFlower();return}if(action==='play')$('#dog').classList.add('playing');if(action==='rest'){$('#dog').classList.add('sleeping');$('#speech').textContent='새근새근… 오늘도 행복했어. z Z';}finish(action);actionTimer=setTimeout(()=>{busy=false;$('#dog').classList.remove('happy','playing','sleeping');if(action==='rest'){state.day++;state.daily=[];state.dailyReward=false;save();render();$('#speech').textContent='좋은 아침! 오늘은 뭘 해볼까?';toast('새로운 하루가 시작됐어요 ☀')}},action==='rest'?3500:1400)}
function placeFlower(){const positions=[[21,65],[76,70],[65,44]];$('#collect').style.left=positions[flowers][0]+'%';$('#collect').style.top=positions[flowers][1]+'%';$('#collect').setAttribute('aria-label',`산책 꽃 ${flowers+1}번째 줍기`)}
$('#collect').onclick=()=>{flowers++;tone();sparkle('✿');$('#scene-caption').textContent=`반짝이는 꽃을 눌러 주세요 · ${flowers} / 3`;if(flowers===3){$('#collect').classList.add('hidden');walking=busy=false;finish('walk');$('#dog').classList.remove('happy');$('#speech').textContent='오늘의 꽃향기, 오래 기억할게.';$('#scene-caption').textContent='강아지를 톡 눌러 마음을 전해 보세요';$('#location').textContent=night?'☾ 별빛이 머무는 정원':'☀ 햇살 가득한 정원'}else placeFlower()};
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>care(b.dataset.action));$('#dog').onclick=()=>care('pet');$('.close').onclick=()=>$('#dialog').close();$('#dialog').addEventListener('click',e=>{if(e.target.id==='growth-close')$('#dialog').close()});$('#night').onclick=()=>{night=!night;$('#scene').classList.toggle('night',night);$('#night').textContent=night?'☀ 낮으로':'☾ 저녁으로';$('#location').textContent=walking?'✿ 꽃향기 나는 산책길':night?'☾ 별빛이 머무는 정원':'☀ 햇살 가득한 정원'};$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'♪':'♫';$('#sound').setAttribute('aria-label',sound?'소리 끄기':'소리 켜기');$('#sound').title=sound?'소리 끄기':'소리 켜기';$('#sound').setAttribute('aria-pressed',String(sound));if(sound)tone();toast(sound?'작은 멜로디를 켰어요':'소리를 껐어요')};
$('#rename').onclick=()=>{modal(`<h2>어떤 이름으로 불러 줄까요?</h2><form id="name-form"><label for="name-input">강아지 이름</label><input id="name-input" maxlength="12" required value="${escape(state.name)}" autocomplete="off"><button class="primary">이 이름으로 부르기</button></form>`);$('#name-form').onsubmit=e=>{e.preventDefault();const name=$('#name-input').value.trim();if(!name)return;state.name=name;save();render();$('#dialog').close();$('#speech').textContent=`${name}! 내 이름, 마음에 들어. ♡`}};
$('#help').onclick=()=>modal('<h2>작은 사랑을 건네는 방법</h2><p>사진 속 강아지를 닮은 작은 친구와 함께하는 느긋한 정원이에요. 이름 옆 연필을 누르면 이름을 바꿀 수 있어요.</p><ul><li>밥 주기 +10, 쓰다듬기 +6, 공놀이 +12, 산책 +18, 낮잠 +8 사랑을 모아요.</li><li>산책에서는 정원에 나타나는 꽃 세 송이를 눌러 보세요.</li><li>사랑 100이면 청소년, 250이면 큰 강아지로 자라요.</li><li>밥·놀이·낮잠을 모두 하면 보너스 +15! 낮잠을 마치면 다음 날이 시작돼요.</li><li>접속하지 않아도 수치가 줄지 않아요. 같은 기기와 브라우저에 자동 저장돼요.</li></ul><p>다 자란 뒤에도 우리의 이야기는 계속됩니다. ♡</p>');
$('#album').onclick=()=>modal(`<h2>우리의 추억 보관함</h2><p>${escape(state.name)}와 함께한 ${state.day}일. 가장 최근 추억 60개를 간직해요.</p>${state.memories.map(m=>`<div class="memory"><small>${m.day}번째 날</small><p>${escape(m.text)}</p></div>`).join('')}`);
$('#settings').onclick=()=>{modal('<h2>소중한 기록 관리</h2><p>이 브라우저에 추억을 저장하고 있어요. 다른 기기로 옮기기 전에 기록을 파일로 간직해 주세요.</p><button class="secondary" id="export">추억 파일 내려받기</button><label class="secondary" for="import" style="display:block;cursor:pointer">추억 파일 불러오기</label><input type="file" id="import" accept="application/json" hidden><button class="secondary" id="reset">처음부터 다시 만나기</button>');$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='pawful-days-memories.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};$('#import').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.version!==1||!Number.isFinite(data.xp)||typeof data.name!=='string')throw Error();stopAction();state=normalize(data);save();render();$('#dialog').close();toast('우리의 추억을 다시 만났어요')}catch{toast('꼬리의 하루에서 저장한 JSON 파일을 선택해 주세요.')}};$('#reset').onclick=()=>{modal('<h2>처음 만난 날로 돌아갈까요?</h2><p>현재 성장과 일기가 지워져요. 간직하고 싶다면 먼저 추억 파일을 내려받아 주세요.</p><button class="primary" id="confirm-reset">기록을 지우고 새로 시작</button><button class="secondary" id="cancel-reset">추억 그대로 두기</button>');$('#cancel-reset').onclick=()=>$('#dialog').close();$('#confirm-reset').onclick=()=>{stopAction();state=freshState();save();render();$('#dialog').close();$('#speech').textContent='우리, 오늘부터 친구 할까? ♡'}}};
function stopAction(){clearTimeout(actionTimer);busy=walking=false;$('#collect').classList.add('hidden');$('#dog').classList.remove('happy','sleeping','playing');$('#scene-caption').textContent='강아지를 톡 눌러 마음을 전해 보세요'}
window.addEventListener('resize',render);render();save();
