import{chromium}from'@playwright/test';import assert from'node:assert/strict';
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const url=process.env.TEST_URL||'http://127.0.0.1:5289/';await page.addInitScript(()=>{const f=sessionStorage.getItem('test-position');if(f){localStorage.setItem('pawful-adventure-v2',f);sessionStorage.removeItem('test-position')}});await page.goto(url);await page.waitForTimeout(400);await page.screenshot({path:'/tmp/adventure-desktop.png'});
const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('pawful-adventure-v2')));
async function flush(){await page.evaluate(()=>window.dispatchEvent(new Event('blur')))}
async function walk(key,time){await page.keyboard.down(key);await page.waitForTimeout(time);await page.keyboard.up(key);await flush()}
async function at(x,y,extra={}){await flush();await page.evaluate(({x,y,extra})=>{const s=JSON.parse(localStorage.getItem('pawful-adventure-v2'));Object.assign(s,{x,y},extra);sessionStorage.setItem('test-position',JSON.stringify(s))},{x,y,extra});await page.reload();await page.waitForTimeout(350)}
await walk('ArrowRight',500);assert.ok((await saved()).x>730,'arrow movement');await walk('w',800);await page.keyboard.press('e');await page.waitForTimeout(200);assert.ok(await page.locator('#talk').isVisible());assert.equal((await saved()).quest,1);await page.keyboard.press('e');
await at(520,795);await page.keyboard.press('e');await page.waitForTimeout(200);assert.equal((await saved()).quest,2);assert.ok((await saved()).food>65);
for(const[x,y]of[[875,900],[1080,995],[1360,905]]){await at(x,y);await walk('w',160)}assert.equal((await saved()).quest,3);assert.equal((await saved()).totalFlowers,3);
await at(1255,1130);await page.keyboard.press('e');await page.waitForTimeout(1100);await walk('d',1600);await walk('w',340);await page.waitForTimeout(250);await flush();assert.equal((await saved()).quest,4,'fetch ball by moving');
await at(835,1550);await page.keyboard.press('e');await page.waitForTimeout(100);assert.equal((await saved()).quest,5);await page.keyboard.press('e');await walk('d',400);
await at(1870,1040);await page.keyboard.press('e');await page.waitForTimeout(100);assert.equal((await saved()).quest,6);await page.keyboard.press('e');
await at(470,670);await page.keyboard.press('e');await page.waitForTimeout(3400);assert.equal((await saved()).quest,7);assert.equal((await saved()).day,2);assert.equal((await saved()).flowers.length,0);
await at(690,800,{xp:248});await at(875,900);await walk('w',200);assert.equal(await page.locator('#stage').textContent(),'어른 강아지');
await page.locator('#rename').click();await page.locator('#name-input').fill('몽실');await page.locator('#name-form button').click();await page.reload();assert.equal(await page.locator('#name').textContent(),'몽실');await page.keyboard.press('m');assert.ok(await page.locator('#big-map').isVisible());await page.locator('#map-close').click();
await at(640,500);await walk('a',400);assert.ok((await saved()).x>=635,'wall collision');
await page.setViewportSize({width:390,height:844});await at(690,800);const before=await saved(),box=await page.locator('#joystick').boundingBox();await page.mouse.move(box.x+56,box.y+56);await page.mouse.down();await page.mouse.move(box.x+90,box.y+56);await page.waitForTimeout(600);await page.mouse.up();await flush();assert.ok((await saved()).x>before.x+45,'mobile joystick moves');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/adventure-mobile.png'});assert.deepEqual(errors,[]);console.log('PASS: walking, world collision, granny dialogue, feeding, flower pickup, running after thrown ball, friend, lake, sleep/day, quests, growth, save/reload, rename, map, mobile joystick, no JS errors');await browser.close();
