import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
p.on("pageerror", (e) => errors.push(e.message));
await p.goto(process.env.TEST_URL || "http://127.0.0.1:5289/");
await p.locator("#start-screen").waitFor({ state: "visible" });
await p.screenshot({ path: "/tmp/pawful-title-v3.png" });
await p.locator("#start").click();
await p.keyboard.down("ArrowRight");
await p.waitForTimeout(650);
await p.keyboard.up("ArrowRight");
await p.screenshot({ path: "/tmp/pawful-play-v3.png" });
await p.keyboard.down(" ");
await p.waitForTimeout(250);
await p.screenshot({ path: "/tmp/pawful-jump-v3.png" });
await p.keyboard.up(" ");
await p.locator("#portrait-button").click();
await p.setViewportSize({ width: 390, height: 844 });
await p.screenshot({ path: "/tmp/pawful-mobile-v3.png" });
console.log(errors);
await b.close();
